import type { ElectrobunConfig } from "electrobun";

export default {
	app: {
		name: "Cash Flow Monitor",
		identifier: "cashflowmonitor.electrobun.dev",
		version: "0.0.1",
	},
	scripts: {
		// Works around electrobun 1.18.1 failing to embed build.win.icon into the executables —
		// see the header of scripts/embed-win-icon.ts. postBuild covers the bundle's launcher.exe
		// and bun.exe; postPackage catches the self-extracting installer. The hook no-ops on
		// non-Windows targets and is safe to run twice.
		postBuild: "scripts/embed-win-icon.ts",
		postPackage: "scripts/embed-win-icon.ts",
	},
	release: {
		// GitHub's /releases/latest/download/ is a stable redirect to the newest
		// non-prerelease release, so this URL survives every new tag. The updater
		// appends the flat artifact names (stable-win-x64-*) that CI uploads.
		baseUrl:
			"https://github.com/niedziolka-andrzej/household-cash-flow-monitor/releases/latest/download",
	},
	build: {
		// Vite builds to dist/, we copy from there
		copy: {
			"dist/index.html": "views/mainview/index.html",
			"dist/assets": "views/mainview/assets",
		},
		// Ignore Vite output in watch mode — HMR handles view rebuilds separately
		watchIgnore: ["dist/**"],
		// App icon: the Lucide "banknote" glyph on the accent indigo. Every file here is
		// generated by `bun run icons` (scripts/generate-icons.ts) and committed, because the
		// release workflow only runs `bun run build`. Each platform wants its own container.
		mac: {
			bundleCEF: false,
			// Converted to AppIcon.icns by iconutil, which only exists on macOS — a Windows or
			// Linux build skips this with a warning rather than failing.
			icons: "assets/icon.iconset",
		},
		linux: {
			bundleCEF: false,
			icon: "assets/icon.png",
		},
		win: {
			bundleCEF: false,
			// Copied to Resources/app.ico, which is also what the installer's desktop shortcut uses.
			icon: "assets/icon.ico",
		},
	},
} satisfies ElectrobunConfig;
