import type { Database } from "bun:sqlite";
// Bun's `type: "text"` import attribute inlines the file's contents as a string at
// build time. We rely on that instead of drizzle-orm's filesystem-based `migrate()`
// (which reads a `drizzle/` folder + journal.json at runtime): the path to that
// folder would differ between `bun run dev` (repo root) and a packaged Electrobun
// build in ways that aren't well-documented yet, whereas a text import bakes the SQL
// straight into the bundle — works identically in dev and in a built app.
//
// The SQL itself is still generated by drizzle-kit from schema.ts (`bun run db:generate`)
// and committed under `drizzle/`; only the *application* mechanism is custom. Adding a
// migration later means: generate it, then add one import + one array entry below.
import migration0000 from "../../../drizzle/0000_stale_eternity.sql" with { type: "text" };
import migration0001 from "../../../drizzle/0001_old_hellion.sql" with { type: "text" };

/** Index + 1 = schema version, tracked via `PRAGMA user_version`. */
const MIGRATIONS: readonly string[] = [migration0000, migration0001];

/** The `user_version` a database is at once this build has migrated it. Tooling that
 * moves database files between channels compares against this to refuse a transfer
 * from a newer schema into an older build. */
export const LATEST_SCHEMA_VERSION = MIGRATIONS.length;

/**
 * Applies every migration above the DB's current `PRAGMA user_version`, each inside
 * its own transaction. Safe to call on every startup — already-applied migrations
 * are skipped, so this is idempotent.
 */
export function runMigrations(sqlite: Database): void {
	const row = sqlite.query("PRAGMA user_version;").get() as { user_version: number };
	const currentVersion = row.user_version;

	for (let i = currentVersion; i < MIGRATIONS.length; i++) {
		const applyMigration = sqlite.transaction(() => {
			sqlite.exec(MIGRATIONS[i]);
			// PRAGMA user_version doesn't take bound parameters; the index is a trusted
			// compile-time constant (array position), never user input.
			sqlite.exec(`PRAGMA user_version = ${i + 1};`);
		});
		applyMigration();
	}
}
